/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dmrc;

/**
 *
 * @author Siddharth
 */
public class facts extends javax.swing.JFrame {

    /**
     * Creates new form facts
     */
    private String[] s=new String[10];
    private int index=0;
    
    public facts() {
        initComponents();
        s[0]="There are no dustbins in Delhi metro";
        s[1]="There are neutral zones in Delhi metro where power cut occurs";
        s[2]="There are even number of coaches in Delhi metro";
        s[3]="DMRC and ICICI bank got together to launch a DMRC debit card ";
        s[4]="Sari Guard feature of escalators";
        s[5]="Assistance for visually impaired";
        s[6]="Wheelchair friendly";
        s[7]="Total of 200 trains covering a total distance of 69,000 kms every day.";
        s[8]="Delhi Metro is one of the very few punctual things that have happened to Delhi";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fact = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(633, 500));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmrc/96-128.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 0, 128, 128);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setText("Do");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 20, 60, 50);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(244, 205, 28));
        jLabel3.setText("?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 20, 40, 50);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("You");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 20, 70, 50);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Know");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 20, 100, 50);

        fact.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        fact.setText("                   \" There are no dustbins in Delhi Metro\"");
        getContentPane().add(fact);
        fact.setBounds(0, 140, 630, 130);

        next.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmrc/next.png"))); // NOI18N
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(300, 290, 60, 50);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 633, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setup(int index){
        fact.setText(s[index]);
    }
    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        // TODO add your handling code here:
        if(index==8) index=-1;
        setup(++index);
        
    }//GEN-LAST:event_nextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel next;
    // End of variables declaration//GEN-END:variables
}
